### PR TITLE
[ready] remove low-quality network_cluster => address_cluster matches

### PR DESCRIPTION
**Pull request by sbma44**
This PR addresses two error conditions that are possible in master:

- low-quality linker matches where the winning `address_cluster` doesn't share a leading letter with the winning `network_cluster` (per @apendleton & @boblannon's suggestions)
- cases where a given `address_cluster` is assigned to multiple `network_cluster`s. A postprocessing step is added that reviews all such network/address groups and removes all but the best text matches.

### CODE REVIEW

**Comment by sbma44** [comment]
Tests pass locally. I will dig into what Circle's complaints are tomorrow.

**Comment by sbma44** [comment]
Circle error was due to postgres 9.5 not supporting `ADD COLUMN IF NOT EXISTS`.

**Comment by mattficke** [comment]
There's a funny hack to use 9.6 on Circle: https://discuss.circleci.com/t/ubuntu-14-04-build-image-update-201701-01/9245

>We only support 9.5 at this moment, but 9.6 was installed and running in the build image accidentally.
We will stop running 9.6 by default but the version will be kept installed. If you wish to use 9.6 instead of 9.5, you can add the following in your circle.yml.

**Comment by sbma44** [comment]
Thanks! I think dockerification will make this less of an issue long-term. But this was just syntax sugar; for now it's easier to simply not use this feature.

**Pull request merged**
